DROP TABLE IF EXISTS EVENT;

CREATE TABLE EVENT (
  EVENT_UID INTEGER NOT NULL,
  TYPE VARCHAR2(20) NOT NULL,
  PUBLIC_IND CHAR(1) NOT NULL,
  REPO_ID INTEGER DEFAULT NULL,
  ACTOR_ID INTEGER(11) NOT NULL,
  CONSTRAINT PK_EVENT_UID PRIMARY KEY (EVENT_UID)
);

CREATE SEQUENCE IF NOT EXISTS SQ_EVENT
	INCREMENT BY 1
	START WITH 1
	NOCYCLE
	NOCACHE;

COMMENT ON TABLE EVENT IS 'Table exists to create record all Events';
COMMENT ON COLUMN EVENT.EVENT_UID IS 'the unique ID of the event (Integer)';
COMMENT ON COLUMN EVENT.TYPE IS 'the type of the event, written in PascalCase (String)';
COMMENT ON COLUMN EVENT.PUBLIC_IND IS 'whether the event is public, either true or false (Boolean)';
COMMENT ON COLUMN EVENT.REPO_ID IS 'the ID of the repository the event belongs to (Integer)';
COMMENT ON COLUMN EVENT.ACTOR_ID IS 'the ID of the user who created the event (Integer)';

GRANT UPDATE ON "EVENT" TO "ORACLE_ADMIN";
GRANT SELECT ON "EVENT" TO "ORACLE_ADMIN";
GRANT INSERT ON "EVENT" TO "ORACLE_ADMIN";
GRANT DELETE ON "EVENT" TO "ORACLE_ADMIN";